In [1]:
##load data from .mat file
#get path
import os
import pandas as pd
import numpy as np
dirname= os.path.abspath(os.getcwd())
df = pd.read_csv(os.path.join(dirname,'biovid_features/fusion_five_classes.csv'))

#df["label"].replace({3:1},inplace=True)
#df["label"].replace({2:1},inplace=True)
#df["label"].replace({4:1},inplace=True)
#df['label'] = np.where(np.arange(len(df)) % 2, 1, 0)
df

subj_id  label  f_rise_time_avg  f_phasic_driver_num_pks  \
0           1      0        19.000000                       16   
1           1      1        12.000000                       28   
2           1      0         7.142857                       28   
3           1      4        16.250000                       16   
4           1      0         6.833333                       24   
...       ...    ...              ...                      ...   
8695       87      2         0.000000                        0   
8696       87      4        10.500000                        8   
8697       87      4         0.000000                        0   
8698       87      4         8.000000                        4   
8699       87      1         0.000000                        0   

      f_phasic_driver_pks_amp_max  f_tonic_max  f_tonic_avg  f_tonic_auc  \
0                        0.402890    -1.269816    -1.855148     7.003343   
1                        1.164678     1.774722    -1.260980   183.825570   
2                        1.262612     2.616708     0.527857   -19.132544   
3                        0.753358     2.592873     0.694303   102.246278   
4                        1.339789     3.857010     2.033824   -13.207073   
...                           ...          ...          ...          ...   
8695                     0.000000     0.535221     0.049688   -21.612143   
8696                     0.157914    -0.141315    -0.361572    -3.590546   
8697                     0.000000    -0.519186    -0.794280    -4.942745   
8698                     0.382271     0.385345    -0.584022    58.641553   
8699                     0.000000     0.387726    -0.169627   -27.456184   

      f_tonic_std  f_phasic_auc  ...  f_phasic_max    hr_mean  hr_median  \
0        0.373149 -3.379127e+00  ...  2.812807e-01  79.275606  91.976013   
1        1.079597 -6.066094e+00  ...  8.745746e-01  77.357555  89.693597   
2        1.540655 -4.363569e+00  ...  8.745746e-01  80.908843  94.523021   
3        0.810289 -1.571363e+01  ...  1.388460e+00  79.668263  92.429973   
4        1.051898 -8.607074e+00  ...  1.388460e+00  83.529634  98.778115   
...           ...           ...  ...           ...        ...        ...   
8695     0.256557 -3.035176e-10  ...  4.133354e-11  72.236690  72.624102   
8696     0.107948 -5.900962e-01  ...  1.074831e-01  73.254964  74.202876   
8697     0.140419 -4.188232e-05  ...  1.396049e-05  73.952049  74.563107   
8698     0.352733 -2.095589e+00  ...  4.180516e-01  70.355194  70.946893   
8699     0.293753 -2.067647e-03  ...  6.892152e-04  70.655333  71.111111   

           sdnn      rmssd         hf         lf     lf_hf    sampen  \
0      0.000000  28.353106        NaN        NaN       NaN       NaN   
1      0.000000  28.251404        NaN        NaN       NaN       NaN   
2     35.723099  25.912021        NaN        NaN       NaN       NaN   
3     40.628413  41.238288        NaN        NaN       NaN       NaN   
4     44.030197  29.642086        NaN        NaN       NaN       NaN   
...         ...        ...        ...        ...       ...       ...   
8695  22.050510  12.667844  35.479651  68.678867  0.406975  1.199561   
8696  18.217519  12.621557  28.778920  62.648329  0.344055  1.187263   
8697  12.232082  11.707196  58.050315  58.505077  0.347413  1.175792   
8698  21.470557  16.341433  53.382828  63.322514  0.480358  1.224576   
8699  12.412985  13.591681  56.800849  74.503966  0.793535  1.227721   

      resp_mean  
0     23.853794  
1     24.624764  
2     23.689002  
3     19.047937  
4     18.286162  
...         ...  
8695  16.688025  
8696  15.700837  
8697  17.395709  
8698  16.881813  
8699  16.832566  

[8700 rows x 22 columns]

In [2]:
df_att = pd.read_csv(os.path.join(dirname,'biovid_features/fusion_five_classes_attention.csv'))
df_att

subj_id  label  f_rise_time_avg  f_phasic_driver_num_pks  \
0            1      0         8.000000                       24   
1            1      0         9.000000                       20   
2            1      0         9.000000                       20   
3            1      0         9.000000                       20   
4            1      0        13.166667                       24   
...        ...    ...              ...                      ...   
52195       87      1         5.000000                        4   
52196       87      1         0.000000                        0   
52197       87      1         0.000000                        0   
52198       87      0         0.000000                        0   
52199       87      1         0.000000                        0   

       f_phasic_driver_pks_amp_max  f_tonic_max  f_tonic_avg  f_tonic_auc  \
0                         0.402890    -1.273036    -2.008337    44.480582   
1                         0.402890    -1.269816    -1.958278    37.363670   
2                         0.402890    -1.269816    -1.919678    23.940284   
3                         0.402890    -1.269816    -1.898813    15.424863   
4                         0.402890    -1.269816    -1.879596    13.981859   
...                            ...          ...          ...          ...   
52195                     0.130534     0.572360     0.107416   -31.346536   
52196                     0.000000     0.572360     0.045790   -31.212172   
52197                     0.000000     0.570253    -0.024952   -30.205279   
52198                     0.000000     0.507783    -0.098578   -28.818787   
52199                     0.000000     0.387726    -0.169627   -27.456184   

       f_tonic_std  f_phasic_auc  ...  f_phasic_max    hr_mean  hr_median  \
0         0.288277     -1.380323  ...      0.281281  78.580244  91.157287   
1         0.338257     -3.676077  ...      0.281281  76.767253  88.914827   
2         0.360418     -3.568680  ...      0.281281  75.800264  88.914827   
3         0.368715     -1.363017  ...      0.281281  78.082900  89.824528   
4         0.373692     -1.658734  ...      0.281281  79.585829  92.407912   
...            ...           ...  ...           ...        ...        ...   
52195     0.317752     -0.858933  ...      0.117793  70.392896  70.783348   
52196     0.329097     -0.552219  ...      0.117793  70.162675  70.783348   
52197     0.324583     -0.122187  ...      0.040496  70.099118  70.783348   
52198     0.309733     -0.015953  ...      0.005318  70.164151  70.783431   
52199     0.293753     -0.002068  ...      0.000689  70.655333  71.111111   

            sdnn      rmssd         hf         lf     lf_hf    sampen  \
0       0.000000  33.712531        NaN        NaN       NaN       NaN   
1       0.000000  28.284698        NaN        NaN       NaN       NaN   
2       0.000000  27.661752        NaN        NaN       NaN       NaN   
3       0.000000  28.069489        NaN        NaN       NaN       NaN   
4       0.000000  30.202847        NaN        NaN       NaN       NaN   
...          ...        ...        ...        ...       ...       ...   
52195  12.819165  14.439960  56.025221  72.573397  0.717494  1.227503   
52196  12.727370  13.553664  56.234130  73.078776  0.734747  1.228128   
52197  12.459946  12.435038  56.395961  73.521233  0.751245  1.229205   
52198  12.121823  12.435150  56.532024  73.936735  0.772165  1.229260   
52199  12.412985  13.591681  56.800849  74.503966  0.793535  1.227721   

       resp_mean  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
...          ...  
52195  16.373021  
52196  17.503421  
52197  16.832566  
52198  16.832566  
52199  16.832566  

[52200 rows x 22 columns]

In [3]:
index_remove = df.loc[df['sdnn'] == 0].index
index_remove = index_remove.union(df.loc[df['label'] == 1].index)
index_remove =index_remove.union(df.loc[df['label'] == 2].index)
index_remove =index_remove.union(df.loc[df['label'] == 3].index)
index_remove = index_remove.unique()
for i in range(6):
    df_att = df_att.drop(index_remove*6+i)

df_att.reset_index(inplace = True)
del df_att["index"]

del df_att["hf"]
del df_att["lf"]
del df_att["lf_hf"]
del df_att["sampen"]
del df_att["resp_mean"]
df_att

subj_id  label  f_rise_time_avg  f_phasic_driver_num_pks  \
0            1      0         8.625000                       32   
1            1      0         9.714286                       28   
2            1      0        10.375000                       32   
3            1      0        11.333333                       36   
4            1      0         5.888889                       36   
...        ...    ...              ...                      ...   
20227       87      4         0.000000                        0   
20228       87      4         0.000000                        0   
20229       87      4         8.000000                        4   
20230       87      0         8.000000                        4   
20231       87      4         8.000000                        4   

       f_phasic_driver_pks_amp_max  f_tonic_max  f_tonic_avg  f_tonic_auc  \
0                         1.262612     2.616708    -0.282394   117.401425   
1                         1.262612     2.616708    -0.093142    66.967444   
2                         1.262612     2.616708     0.065434    32.850434   
3                         1.262612     2.616708     0.207707    10.747282   
4                         1.262612     2.616708     0.356549    -5.607385   
...                            ...          ...          ...          ...   
20227                     0.000000    -0.379742    -0.678210    -0.054096   
20228                     0.000000    -0.379742    -0.680979    16.215023   
20229                     0.382271    -0.113973    -0.670131    33.506344   
20230                     0.382271     0.162541    -0.638458    48.375692   
20231                     0.382271     0.385345    -0.584022    58.641553   

       f_tonic_std  f_phasic_auc  f_phasic_std  f_phasic_avg  f_phasic_max  \
0         1.899071     -8.382821      0.219574      0.146390      0.874575   
1         1.899225     -4.618948      0.219252      0.147078      0.874575   
2         1.861146     14.777648      0.222540      0.163662      0.874575   
3         1.801050      7.796456      0.224705      0.187988      0.874575   
4         1.704616     -8.475854      0.222037      0.194310      0.874575   
...            ...           ...           ...           ...           ...   
20227     0.169379     17.908608      0.055743      0.018876      0.315489   
20228     0.167204     21.204083      0.110662      0.040308      0.418052   
20229     0.191203      2.919214      0.121602      0.053720      0.418052   
20230     0.260287     -2.546297      0.121056      0.055782      0.418052   
20231     0.352733     -2.095589      0.120786      0.056440      0.418052   

         hr_mean  hr_median       sdnn      rmssd  
0      76.313930  88.411839  38.867445  34.174950  
1      76.140459  87.521352  37.274752  32.785370  
2      76.510367  88.163855  37.330096  37.488433  
3      77.412963  89.302326  33.509674  33.498172  
4      79.402922  94.523021  33.975371  32.440594  
...          ...        ...        ...        ...  
20227  70.040553  70.620721  20.429833  16.820620  
20228  70.167057  70.620721  21.120357  16.681786  
20229  70.456344  70.620721  21.382417  16.681928  
20230  70.290477  70.620721  21.818847  16.341433  
20231  70.355194  70.946893  21.470557  16.341433  

[20232 rows x 17 columns]

In [4]:
df = df.loc[~(df['sdnn'] == 0)]
df = df.loc[~(df['label'] == 2)]
df = df.loc[~(df['label'] == 3)]
df = df.loc[~(df['label'] == 1)]
df["label"].replace({4:1},inplace=True)
df.reset_index(inplace = True)
del df["index"]

del df["hf"]
del df["lf"]
del df["lf_hf"]
del df["sampen"]
del df["resp_mean"]
df

subj_id  label  f_rise_time_avg  f_phasic_driver_num_pks  \
0           1      0         7.142857                       28   
1           1      1        16.250000                       16   
2           1      0         6.833333                       24   
3           1      1        23.800000                       20   
4           1      0        20.500000                       24   
...       ...    ...              ...                      ...   
3367       87      1         1.000000                        8   
3368       87      1         2.500000                        8   
3369       87      1        10.500000                        8   
3370       87      1         0.000000                        0   
3371       87      1         8.000000                        4   

      f_phasic_driver_pks_amp_max  f_tonic_max  f_tonic_avg  f_tonic_auc  \
0                        1.262612     2.616708     0.527857   -19.132544   
1                        0.753358     2.592873     0.694303   102.246278   
2                        1.339789     3.857010     2.033824   -13.207073   
3                        0.722952     1.967102     1.384223    30.394666   
4                        2.571332     2.881669     1.239165   -64.321602   
...                           ...          ...          ...          ...   
3367                     0.024172    -0.261930    -0.725573   -12.448270   
3368                     0.136949     0.614219     0.050346   -13.893852   
3369                     0.157914    -0.141315    -0.361572    -3.590546   
3370                     0.000000    -0.519186    -0.794280    -4.942745   
3371                     0.382271     0.385345    -0.584022    58.641553   

      f_tonic_std  f_phasic_auc  f_phasic_std  f_phasic_avg  f_phasic_max  \
0        1.540655     -4.363569      0.224529  1.811178e-01      0.874575   
1        0.810289    -15.713629      0.397342  3.702333e-01      1.388460   
2        1.051898     -8.607074      0.362987  3.513889e-01      1.388460   
3        0.404948      3.456608      0.403696  3.803392e-01      1.455991   
4        0.963312    -15.775205      0.424365  3.237339e-01      1.455991   
...           ...           ...           ...           ...           ...   
3367     0.250256      0.097972      0.002752  9.983321e-04      0.011812   
3368     0.265719     -0.467891      0.022223  9.414397e-03      0.082994   
3369     0.107948     -0.590096      0.025242  9.872606e-03      0.107483   
3370     0.140419     -0.000042      0.000002  5.817107e-07      0.000014   
3371     0.352733     -2.095589      0.120786  5.644026e-02      0.418052   

        hr_mean  hr_median       sdnn      rmssd  
0     80.908843  94.523021  35.723099  25.912021  
1     79.668263  92.429973  40.628413  41.238288  
2     83.529634  98.778115  44.030197  29.642086  
3     74.165545  86.541376  46.739651  31.179286  
4     72.418200  84.281269  45.729534  31.767774  
...         ...        ...        ...        ...  
3367  71.757050  72.112698  11.000550  16.763017  
3368  74.739240  75.110036  12.994361  13.045666  
3369  73.254964  74.202876  18.217519  12.621557  
3370  73.952049  74.563107  12.232082  11.707196  
3371  70.355194  70.946893  21.470557  16.341433  

[3372 rows x 17 columns]

In [5]:
df_labels = pd.read_csv(os.path.join(dirname,'biovid_features/sens_temp.csv'))
df_labels
import scipy.stats as stats
input_th_z = stats.zscore(df_labels.pain_threshold)
input_to_z = stats.zscore(df_labels.pain_tolerance)
input_th_to_z = (input_th_z+input_to_z)/2
print(input_th_to_z.shape)

(87,)


In [6]:
import numpy as np
import copy

step = 6
seq_len = 6

input_data = []
input_label = []
input_subj = []

#for each subject
person_count = 0
for subj in np.unique(df.subj_id.values):
    idx = df.index[df['subj_id']==subj]
    data2D = df.iloc[idx,2:].values
    label2D = df.iloc[idx,1].values
    
   # data_len = len(data2D) - seq_len + 1
   # data2D = data2D[seq_len-1:,:]
   # label2D = label2D[seq_len-1:]
    
    print(data2D.shape)
    print(np.count_nonzero(label2D==1) )
    
    person_sens_threshold = np.full((data2D.shape[0],1),input_th_to_z[person_count])
    person_count = person_count+1
    #update data2D with personal sensitivity
    data2D = np.concatenate((person_sens_threshold,data2D),axis = 1) 
    print(data2D.shape)

    input_data.append(data2D)
    input_label.append(label2D)
    input_subj.append(subj)
    
    
at_input_data = []
at_input_label = []
at_input_subj = []

#for each subject
for subj in np.unique(df_att.subj_id.values):
    idx = df_att.index[df_att['subj_id']==subj]
    data2D_ = df_att.iloc[idx,2:].values
    label2D_ = df_att.iloc[idx,1].values
    print(data2D_.shape)
    
    #补位，为了与input_data维度保持一致
    patch_data = np.zeros((data2D_.shape[0],1))
    
    #update data2D with personalHRV
    data2D_ = np.concatenate((patch_data,data2D_),axis = 1) #column0:3 personal HRV, column3:end features
    
    #data_len = len(data2D_) - seq_len + 1
    data_len = int(len(data2D_)/6 )   #initial an empty array 其他的notebook，改这里
    print(data_len)
    data3D=np.empty((data_len,seq_len,data2D_.shape[1]))#empty
    label3D=np.empty((data_len,))#many to one label
    
    for i in range(data_len):
        data3D[i,:,:]=data2D_[i*step : i*step+seq_len,:]
        label3D[i]=label2D_[i*step+seq_len-1] #-1
    
    print(data3D.shape)
    #print(np.count_nonzero(label3D))
    
    at_input_data.append(data3D)
    at_input_label.append(label3D)
    at_input_subj.append(subj)

#leave subject out cv, LSOCV
def LSOCV(input_subj,input_data,input_label,test_subj):
    test_index=input_subj.index(test_subj)
    test_data=input_data[test_index]
    test_label=input_label[test_index]
    
    train_data=copy.deepcopy(input_data)
    train_data.pop(test_index)
    train_data=np.vstack(train_data)

    train_label=copy.deepcopy(input_label)
    train_label.pop(test_index)
    train_label=np.hstack(train_label)
    
    return train_data,train_label,test_data,test_label

#leave subject out cv with random subject hold-out for tuning
def LSOCV_TUNE(input_subj,input_data,input_label,test_subj):
    #print(test_subj)
    test_index=input_subj.index(test_subj)
    #print(test_index)
    test_data=input_data[test_index]
    test_label=input_label[test_index]   
    
    tune_data=[]
    tune_label=[]
    
    train_data=[]
    train_label=[]
    
    full_subj = input_subj
    full_subj = np.delete(full_subj,test_subj-1)
    #print(full_subj)
    
    hold_out_subj = np.random.choice(full_subj,size = 18, replace = False)
    #print(hold_out_subj)
    #print(hold_out)
    for subj in hold_out_subj:   
        index_hold = input_subj.index(subj)
        #print(index_keep)
        tune_data.append(input_data[index_hold])
        tune_label.append(input_label[index_hold])
        
    train_subj = [i for i in full_subj if i not in hold_out_subj]
    #print(train_subj)
    for subj in train_subj:   
        index_train = input_subj.index(subj)
        #print(index_keep)
        train_data.append(input_data[index_train])
        train_label.append(input_label[index_train])
        
    train_data = np.vstack(train_data)
    train_label = np.hstack(train_label)
    
    tune_data = np.vstack(tune_data)
    tune_label = np.hstack(tune_label)
    
    return train_data,train_label,tune_data,tune_label,test_data,test_label

(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(38, 15)
19
(38, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(38, 15)
19
(38, 16)
(38, 15)
19
(38, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(38, 15)
19
(38, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(38, 15)
19
(38, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(38, 15)
19
(38, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(38, 15)
19
(38, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(38, 15)
19
(38, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(39, 16)
(39, 15)
20
(

In [7]:
import torch
import torch.nn as nn
#from pytorch_model_summary import summary

# input_size: the number of expected features in the input x
# batch_first – If True, then the input and output tensors are provided as (batch, seq, feature). 
class PainNet(nn.Module):
    def __init__(self, output_size, input_size,channel_num):
        super(PainNet, self).__init__()
        self.input_size = input_size
        self.output_size = output_size
        
        self.fc1 = nn.Sequential(nn.Linear(input_size-1, 32),
                               nn.Sigmoid(),
                               nn.Linear(32, 16),
                               nn.Sigmoid(),
                               nn.Linear(16, 6),
                               nn.Sigmoid())
        #for attention
        self.bn = nn.BatchNorm2d(channel_num)
        #nn.init.kaiming_normal_(self.bn.weight)
        nn.init.normal_(self.bn.weight.data, mean=1, std=0.02)
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
           
        self.fc2 = nn.Sequential(nn.Conv2d(channel_num, 1, 1, bias=False),
                               nn.ReLU(),
                               nn.Conv2d(1, channel_num, 1, bias=False))
        self.ChannelAttention = nn.Sigmoid()
        for p in self.fc2.parameters():
            nn.init.kaiming_normal_(p)
            
        self.bn1D_input = nn.BatchNorm1d(input_size-1)
        self.bn1D_output = nn.BatchNorm1d(6+1)
        self.output = nn.Sequential(nn.Linear(6+1,output_size),
                                    nn.Sigmoid())

    
    def forward(self, x):
        batch_size = x. size(0)
        #print(x.shape)
        attention = x[:,1:x.size(1),1:x.size(2)].float()#D2: 0,1,2补位，3~attention
        #print(attention.shape)
        x_data = x[:,0,1:x.size(2)].float()#D2: 0,1,2 sensitivity, 3~ 数据
        personalize = x[:,0,0:1].float()
        
        #修改attention维度
        attention = torch.swapaxes(attention,2,1)
        #print(attention.shape)
        attention = torch.unsqueeze(attention, axis = 3)
        #print(attention.shape)
        
        x_ca = self.bn(attention)
        avg_out = self.fc2(self.avg_pool(x_ca))
        #max_out = self.fc2(self.max_pool(x_ca))
        #temp = avg_out + max_out
        temp = avg_out
        ca = self.ChannelAttention(temp)
        ca = ca.squeeze()
        #print(ca.shape)
        x_data = self.bn1D_input(x_data)
        x_data = ca*x_data
        #print(x_data.shape)
        #print(personalize.shape)
        out = self.fc1(x_data)
        personalize_x = torch.cat((out,personalize),1)
        personalize_x = self.bn1D_output(personalize_x)
        out = self.output(personalize_x)
        
        return out     
    
activation = {}
def get_activation(name):
    def hook(model, input, output):
        activation[name] = output.detach()
    return hook

In [8]:
def Perf_evaluation(data_loader, batch_size):
    num_correct = 0
    count=0
    
    for inputs, labels in data_loader:
        count=count+1
        inputs, labels = inputs.to(device), labels.to(device)
        output = model(inputs)
        pred_01 = torch.round(output.squeeze())  # Rounds the output to 0/1
        correct_tensor = pred_01.eq(labels.float().view_as(pred_01))
        correct = np.squeeze(correct_tensor.cpu().numpy())
        num_correct += np.sum(correct)
        pred_01=pred_01.cpu().detach().numpy()
        pred_01=np.reshape(pred_01,(-1))
        
        pred = output.squeeze()
        pred=pred.cpu().detach().numpy()
        pred=np.reshape(pred,(-1))
        
        labels=np.reshape(labels.cpu(),(-1))
        if count==1:
            all_pred=pred
            all_pred_01 = pred_01
            all_label=labels

        else:
            all_pred=np.hstack((all_pred,pred))
            all_label=np.hstack((all_label,labels))
            all_pred_01=np.hstack((all_pred_01,pred_01))

    acc = num_correct/(count*batch_size)

    #print("Accuracy: {:.3f}%".format(acc*100))
    #print("Confusion matrix:")
    #print(confusion_matrix(all_label, all_pred))
    
    return all_pred, all_pred_01, all_label

In [9]:
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, f1_score, roc_auc_score,accuracy_score
from sklearn.metrics import confusion_matrix


for i in np.unique(input_subj):
    if(torch.cuda.is_available()):
        device="cuda:1"
        #device="cpu"
    else:
        device="cpu"
    
    print(device)

    input_size = data2D.shape[1]
    output_size = 1
    criterion = nn.BCELoss()
    def adjust_learning_rate(epoch):
        lr = 0.01*(0.1**(epoch//50))
        return lr
    epochs = 100
    print_every = 10
    clip = 5
    
    
    if i>-1: #以防需要筛选:     
        model = PainNet(output_size, input_size,channel_num = input_size-1)
        model.to(device)
        trained_model_dict = torch.load('./biovid_binary_pretrained.pt')
        #print(trained_model_dict)
        model.load_state_dict(trained_model_dict)
        model.fc1[0].weight.requires_grad = False
        model.fc1[0].bias.requires_grad = False
        #model.fc1[2].weight.requires_grad = False
        #model.fc1[2].bias.requires_grad = False
        
        model.ChannelAttention.register_forward_hook(get_activation('ChannelAttention'))
        
        counter = 0
        acc_min = 0
        test_subj = i
        print(len(input_subj))
        print(len(input_data))
        print(len(input_label))

        print("test_subject: {}".format(test_subj))
        
      #  #leave-subject-out cross-validation, in training phase 80% of training dataset train, 20% person tuning
      #  [train_data,train_label,tune_data, tune_label,test_data,test_label]=LSOCV_TUNE(input_subj,input_data,
      #                                                                                 input_label,test_subj=test_subj)
      #  print(train_data.shape, train_label.shape, tune_data.shape, tune_label.shape,
      #       test_data.shape, test_label.shape)
        
        #leave-subject-out cross-validation, in training phase 80% of training dataset train, 20% data tuning
        [train_data,train_label,test_data,test_label]=LSOCV(input_subj,input_data,input_label,test_subj=test_subj)
        [train_data,tune_data, train_label, tune_label]= train_test_split(train_data,train_label, test_size = 0.2, random_state = 42)
        
        print(train_data.shape, train_label.shape, tune_data.shape, tune_label.shape,
             test_data.shape, test_label.shape)
        [train_attention,train_att_label,test_attention,test_att_label]=LSOCV(input_subj,at_input_data,at_input_label,test_subj=test_subj)
        [train_attention,tune_attention, train_att_label, tune_att_label]= train_test_split(
            train_attention,train_att_label, test_size = 0.2, random_state = 42)
        
        train_data = np.reshape(train_data,(train_data.shape[0],1,train_data.shape[1]))
        train_data = np.concatenate((train_data,train_attention),axis = 1)
        tune_data = np.reshape(tune_data,(tune_data.shape[0],1,tune_data.shape[1]))
        tune_data = np.concatenate((tune_data,tune_attention),axis = 1)
        test_data = np.reshape(test_data,(test_data.shape[0],1,test_data.shape[1]))
        test_data = np.concatenate((test_data,test_attention),axis = 1)
        
        train_label = torch.from_numpy(train_label)
        tune_label = torch.from_numpy(tune_label)
        test_label = torch.from_numpy(test_label)
                
        #对不同类的样本赋予权重，然后进行权重采样
        #count num of different classes

        print('target train 0/1: {}/{}'.format(
            (train_label == 0).sum(), (train_label != 1).sum()))
      
        train_label = train_label.long()
       
        test_label = test_label.long()
        
        batch_size = test_label.shape[0]
        print(train_data.shape,train_label.shape,tune_data.shape,tune_label.shape,test_data.shape,test_label.shape)
        print(type(train_data),type(train_label), type(test_data), type(test_label))

        dataset_training = TensorDataset(torch.from_numpy(train_data),train_label)
        dataset_tuning = TensorDataset(torch.from_numpy(tune_data),tune_label)
        dataset_test = TensorDataset(torch.from_numpy(test_data),test_label)

        train_loader = DataLoader(dataset_training, shuffle=False, batch_size=batch_size, drop_last=False)
        tuning_loader = DataLoader(dataset_tuning, shuffle=False, batch_size=batch_size, drop_last=False)
        test_loader = DataLoader(dataset_test, shuffle=False, batch_size=batch_size, drop_last=False)
    
        model.train()
    
        for i in range(epochs):
            learning_rate = adjust_learning_rate(i)
            optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)
    
            for inputs, labels in train_loader:
                model.train()
                counter += 1
        
                inputs, labels = inputs.to(device), labels.to(device)
            
                model.zero_grad()
                output = model(inputs)
                loss = criterion(output.squeeze(), labels.float())
                loss.backward()
                nn.utils.clip_grad_norm_(model.parameters(), clip)
                optimizer.step()
       
                if counter%print_every == 0:
                    #evaluate on validation data
                    model.eval()
                    [tuning_pred, tuning_pred_01, tuning_label] = Perf_evaluation(tuning_loader, batch_size)
                    acc = accuracy_score(tuning_label, tuning_pred_01);
                    if acc>acc_min:
                        [test_pred, test_pred_01, test_label] = Perf_evaluation(test_loader, batch_size)
                        acc_test = accuracy_score(test_label, test_pred_01);
                        print("Epoch: {}/{}...".format(i+1, epochs),
                          "Step: {}...".format(counter),
                          "Loss: {:.6f}...".format(loss.item()))
                        #torch.save(model.state_dict(), './test.pt')
                        print("Tuning acc improved({:.3f}-->{:.3f}). Saving model...".format(acc_min, acc))
                        print("Test acc {:.3f}".format(acc_test))
                        print("Confusion matrix:")
                        print(confusion_matrix(test_label, test_pred_01))
                        acc_min = acc
                        test_result = pd.DataFrame({"pred":test_pred,"label":test_label, "pred_01":test_pred_01})
                        test_save_path = 'eswa_revision/F_binary_NN_dynatt_sensmeasure_04/test'+str(test_subj)+'.xlsx'
                        test_result.to_excel(os.path.join(dirname,test_save_path))

cuda:1
87
87
87
test_subject: 1
(2666, 16) (2666,) (667, 16) (667,) (39, 16) (39,)
target train 0/1: 1318/1318
(2666, 7, 16) torch.Size([2666]) (667, 7, 16) torch.Size([667]) (39, 7, 16) torch.Size([39])
<class 'numpy.ndarray'> <class 'torch.Tensor'> <class 'numpy.ndarray'> <class 'torch.Tensor'>
Epoch: 1/100... Step: 10... Loss: 0.715812...
Tuning acc improved(0.000-->0.474). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 1/100... Step: 30... Loss: 0.522114...
Tuning acc improved(0.474-->0.561). Saving model...
Test acc 0.667
Confusion matrix:
[[19  0]
 [13  7]]
Epoch: 1/100... Step: 40... Loss: 0.459597...
Tuning acc improved(0.561-->0.682). Saving model...
Test acc 0.795
Confusion matrix:
[[19  0]
 [ 8 12]]
Epoch: 1/100... Step: 50... Loss: 0.502144...
Tuning acc improved(0.682-->0.709). Saving model...
Test acc 0.846
Confusion matrix:
[[19  0]
 [ 6 14]]
Epoch: 2/100... Step: 100... Loss: 0.508979...
Tuning acc improved(0.709-->0.745). Saving model...
Tes

Epoch: 2/100... Step: 90... Loss: 0.583311...
Tuning acc improved(0.697-->0.784). Saving model...
Test acc 0.974
Confusion matrix:
[[19  0]
 [ 1 18]]
Epoch: 2/100... Step: 110... Loss: 0.354402...
Tuning acc improved(0.784-->0.796). Saving model...
Test acc 0.974
Confusion matrix:
[[19  0]
 [ 1 18]]
Epoch: 3/100... Step: 170... Loss: 0.282700...
Tuning acc improved(0.796-->0.799). Saving model...
Test acc 0.974
Confusion matrix:
[[19  0]
 [ 1 18]]
Epoch: 4/100... Step: 220... Loss: 0.390761...
Tuning acc improved(0.799-->0.801). Saving model...
Test acc 0.974
Confusion matrix:
[[19  0]
 [ 1 18]]
Epoch: 4/100... Step: 240... Loss: 0.711110...
Tuning acc improved(0.801-->0.804). Saving model...
Test acc 0.974
Confusion matrix:
[[19  0]
 [ 1 18]]
Epoch: 5/100... Step: 290... Loss: 0.472238...
Tuning acc improved(0.804-->0.810). Saving model...
Test acc 0.974
Confusion matrix:
[[19  0]
 [ 1 18]]
Epoch: 6/100... Step: 360... Loss: 0.539659...
Tuning acc improved(0.810-->0.816). Saving model

Epoch: 12/100... Step: 800... Loss: 0.414084...
Tuning acc improved(0.846-->0.847). Saving model...
Test acc 0.667
Confusion matrix:
[[14  5]
 [ 8 12]]
Epoch: 13/100... Step: 870... Loss: 0.417776...
Tuning acc improved(0.847-->0.850). Saving model...
Test acc 0.667
Confusion matrix:
[[13  6]
 [ 7 13]]
Epoch: 27/100... Step: 1840... Loss: 0.342272...
Tuning acc improved(0.850-->0.856). Saving model...
Test acc 0.641
Confusion matrix:
[[14  5]
 [ 9 11]]
Epoch: 28/100... Step: 1910... Loss: 0.381742...
Tuning acc improved(0.856-->0.858). Saving model...
Test acc 0.667
Confusion matrix:
[[14  5]
 [ 8 12]]
Epoch: 43/100... Step: 2910... Loss: 0.341831...
Tuning acc improved(0.858-->0.862). Saving model...
Test acc 0.641
Confusion matrix:
[[15  4]
 [10 10]]
Epoch: 51/100... Step: 3470... Loss: 0.423638...
Tuning acc improved(0.862-->0.868). Saving model...
Test acc 0.641
Confusion matrix:
[[14  5]
 [ 9 11]]
Epoch: 51/100... Step: 3510... Loss: 0.311715...
Tuning acc improved(0.868-->0.870).

Epoch: 1/100... Step: 30... Loss: 0.536324...
Tuning acc improved(0.481-->0.564). Saving model...
Test acc 0.462
Confusion matrix:
[[18  1]
 [20  0]]
Epoch: 1/100... Step: 40... Loss: 0.466160...
Tuning acc improved(0.564-->0.657). Saving model...
Test acc 0.538
Confusion matrix:
[[18  1]
 [17  3]]
Epoch: 1/100... Step: 50... Loss: 0.448865...
Tuning acc improved(0.657-->0.700). Saving model...
Test acc 0.615
Confusion matrix:
[[17  2]
 [13  7]]
Epoch: 1/100... Step: 60... Loss: 0.394743...
Tuning acc improved(0.700-->0.720). Saving model...
Test acc 0.590
Confusion matrix:
[[16  3]
 [13  7]]
Epoch: 2/100... Step: 70... Loss: 0.422247...
Tuning acc improved(0.720-->0.747). Saving model...
Test acc 0.692
Confusion matrix:
[[13  6]
 [ 6 14]]
Epoch: 2/100... Step: 110... Loss: 0.503158...
Tuning acc improved(0.747-->0.757). Saving model...
Test acc 0.769
Confusion matrix:
[[17  2]
 [ 7 13]]
Epoch: 2/100... Step: 120... Loss: 0.677572...
Tuning acc improved(0.757-->0.769). Saving model...


Epoch: 3/100... Step: 180... Loss: 0.438442...
Tuning acc improved(0.753-->0.763). Saving model...
Test acc 0.947
Confusion matrix:
[[18  1]
 [ 1 18]]
Epoch: 3/100... Step: 200... Loss: 0.382611...
Tuning acc improved(0.763-->0.772). Saving model...
Test acc 0.947
Confusion matrix:
[[18  1]
 [ 1 18]]
Epoch: 4/100... Step: 250... Loss: 0.500551...
Tuning acc improved(0.772-->0.774). Saving model...
Test acc 0.947
Confusion matrix:
[[18  1]
 [ 1 18]]
Epoch: 4/100... Step: 260... Loss: 0.373477...
Tuning acc improved(0.774-->0.793). Saving model...
Test acc 0.947
Confusion matrix:
[[18  1]
 [ 1 18]]
Epoch: 5/100... Step: 320... Loss: 0.320812...
Tuning acc improved(0.793-->0.795). Saving model...
Test acc 0.947
Confusion matrix:
[[18  1]
 [ 1 18]]
Epoch: 5/100... Step: 350... Loss: 0.447501...
Tuning acc improved(0.795-->0.798). Saving model...
Test acc 0.974
Confusion matrix:
[[19  0]
 [ 1 18]]
Epoch: 6/100... Step: 360... Loss: 0.507353...
Tuning acc improved(0.798-->0.802). Saving mode

Epoch: 18/100... Step: 1180... Loss: 0.308040...
Tuning acc improved(0.820-->0.822). Saving model...
Test acc 0.949
Confusion matrix:
[[19  0]
 [ 2 18]]
Epoch: 18/100... Step: 1200... Loss: 0.388085...
Tuning acc improved(0.822-->0.826). Saving model...
Test acc 0.949
Confusion matrix:
[[18  1]
 [ 1 19]]
Epoch: 18/100... Step: 1230... Loss: 0.326478...
Tuning acc improved(0.826-->0.838). Saving model...
Test acc 0.949
Confusion matrix:
[[19  0]
 [ 2 18]]
Epoch: 24/100... Step: 1620... Loss: 0.315902...
Tuning acc improved(0.838-->0.844). Saving model...
Test acc 0.949
Confusion matrix:
[[18  1]
 [ 1 19]]
Epoch: 31/100... Step: 2100... Loss: 0.249394...
Tuning acc improved(0.844-->0.849). Saving model...
Test acc 0.949
Confusion matrix:
[[18  1]
 [ 1 19]]
Epoch: 43/100... Step: 2910... Loss: 0.351390...
Tuning acc improved(0.849-->0.850). Saving model...
Test acc 0.974
Confusion matrix:
[[19  0]
 [ 1 19]]
Epoch: 44/100... Step: 2980... Loss: 0.403816...
Tuning acc improved(0.850-->0.855

Epoch: 13/100... Step: 840... Loss: 0.352702...
Tuning acc improved(0.826-->0.828). Saving model...
Test acc 0.872
Confusion matrix:
[[14  5]
 [ 0 20]]
Epoch: 20/100... Step: 1370... Loss: 0.346360...
Tuning acc improved(0.828-->0.832). Saving model...
Test acc 0.846
Confusion matrix:
[[13  6]
 [ 0 20]]
Epoch: 25/100... Step: 1670... Loss: 0.665321...
Tuning acc improved(0.832-->0.834). Saving model...
Test acc 0.872
Confusion matrix:
[[14  5]
 [ 0 20]]
Epoch: 35/100... Step: 2360... Loss: 0.615497...
Tuning acc improved(0.834-->0.838). Saving model...
Test acc 0.872
Confusion matrix:
[[14  5]
 [ 0 20]]
Epoch: 41/100... Step: 2800... Loss: 0.435741...
Tuning acc improved(0.838-->0.844). Saving model...
Test acc 0.846
Confusion matrix:
[[13  6]
 [ 0 20]]
Epoch: 42/100... Step: 2870... Loss: 0.367432...
Tuning acc improved(0.844-->0.849). Saving model...
Test acc 0.846
Confusion matrix:
[[13  6]
 [ 0 20]]
Epoch: 50/100... Step: 3420... Loss: 0.284334...
Tuning acc improved(0.849-->0.859)

Epoch: 97/100... Step: 6640... Loss: 0.329770...
Tuning acc improved(0.850-->0.852). Saving model...
Test acc 0.974
Confusion matrix:
[[18  1]
 [ 0 20]]
cuda:1
87
87
87
test_subject: 17
(2666, 16) (2666,) (667, 16) (667,) (39, 16) (39,)
target train 0/1: 1314/1314
(2666, 7, 16) torch.Size([2666]) (667, 7, 16) torch.Size([667]) (39, 7, 16) torch.Size([39])
<class 'numpy.ndarray'> <class 'torch.Tensor'> <class 'numpy.ndarray'> <class 'torch.Tensor'>
Epoch: 1/100... Step: 10... Loss: 0.693335...
Tuning acc improved(0.000-->0.480). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 1/100... Step: 30... Loss: 0.514313...
Tuning acc improved(0.480-->0.556). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 1/100... Step: 40... Loss: 0.490732...
Tuning acc improved(0.556-->0.669). Saving model...
Test acc 0.590
Confusion matrix:
[[19  0]
 [16  4]]
Epoch: 1/100... Step: 50... Loss: 0.460322...
Tuning acc improved(0.669-->0.711). Saving model...


Epoch: 10/100... Step: 630... Loss: 0.336207...
Tuning acc improved(0.822-->0.823). Saving model...
Test acc 0.949
Confusion matrix:
[[19  0]
 [ 2 18]]
Epoch: 12/100... Step: 810... Loss: 0.495930...
Tuning acc improved(0.823-->0.825). Saving model...
Test acc 0.949
Confusion matrix:
[[19  0]
 [ 2 18]]
Epoch: 12/100... Step: 820... Loss: 0.390723...
Tuning acc improved(0.825-->0.832). Saving model...
Test acc 0.949
Confusion matrix:
[[19  0]
 [ 2 18]]
Epoch: 17/100... Step: 1160... Loss: 0.311671...
Tuning acc improved(0.832-->0.834). Saving model...
Test acc 0.923
Confusion matrix:
[[19  0]
 [ 3 17]]
Epoch: 20/100... Step: 1370... Loss: 0.330481...
Tuning acc improved(0.834-->0.841). Saving model...
Test acc 0.923
Confusion matrix:
[[19  0]
 [ 3 17]]
Epoch: 24/100... Step: 1650... Loss: 0.413458...
Tuning acc improved(0.841-->0.847). Saving model...
Test acc 0.923
Confusion matrix:
[[18  1]
 [ 2 18]]
Epoch: 33/100... Step: 2250... Loss: 0.415677...
Tuning acc improved(0.847-->0.858). 

Epoch: 1/100... Step: 30... Loss: 0.470197...
Tuning acc improved(0.478-->0.571). Saving model...
Test acc 0.564
Confusion matrix:
[[19  0]
 [17  3]]
Epoch: 1/100... Step: 40... Loss: 0.487473...
Tuning acc improved(0.571-->0.667). Saving model...
Test acc 0.846
Confusion matrix:
[[19  0]
 [ 6 14]]
Epoch: 1/100... Step: 50... Loss: 0.406035...
Tuning acc improved(0.667-->0.715). Saving model...
Test acc 0.872
Confusion matrix:
[[19  0]
 [ 5 15]]
Epoch: 2/100... Step: 70... Loss: 0.363108...
Tuning acc improved(0.715-->0.721). Saving model...
Test acc 0.949
Confusion matrix:
[[19  0]
 [ 2 18]]
Epoch: 2/100... Step: 110... Loss: 0.458011...
Tuning acc improved(0.721-->0.777). Saving model...
Test acc 0.949
Confusion matrix:
[[19  0]
 [ 2 18]]
Epoch: 5/100... Step: 320... Loss: 0.304829...
Tuning acc improved(0.777-->0.780). Saving model...
Test acc 0.974
Confusion matrix:
[[18  1]
 [ 0 20]]
Epoch: 6/100... Step: 380... Loss: 0.335214...
Tuning acc improved(0.780-->0.781). Saving model...

Epoch: 56/100... Step: 3860... Loss: 0.416352...
Tuning acc improved(0.859-->0.862). Saving model...
Test acc 0.795
Confusion matrix:
[[15  4]
 [ 4 16]]
Epoch: 63/100... Step: 4280... Loss: 0.213319...
Tuning acc improved(0.862-->0.864). Saving model...
Test acc 0.795
Confusion matrix:
[[15  4]
 [ 4 16]]
Epoch: 66/100... Step: 4490... Loss: 0.229528...
Tuning acc improved(0.864-->0.867). Saving model...
Test acc 0.769
Confusion matrix:
[[14  5]
 [ 4 16]]
Epoch: 81/100... Step: 5530... Loss: 0.421167...
Tuning acc improved(0.867-->0.868). Saving model...
Test acc 0.821
Confusion matrix:
[[16  3]
 [ 4 16]]
Epoch: 82/100... Step: 5600... Loss: 0.305889...
Tuning acc improved(0.868-->0.870). Saving model...
Test acc 0.795
Confusion matrix:
[[15  4]
 [ 4 16]]
cuda:1
87
87
87
test_subject: 25
(2666, 16) (2666,) (667, 16) (667,) (39, 16) (39,)
target train 0/1: 1314/1314
(2666, 7, 16) torch.Size([2666]) (667, 7, 16) torch.Size([667]) (39, 7, 16) torch.Size([39])
<class 'numpy.ndarray'> <class

Epoch: 11/100... Step: 730... Loss: 0.390118...
Tuning acc improved(0.820-->0.828). Saving model...
Test acc 0.872
Confusion matrix:
[[19  0]
 [ 5 15]]
Epoch: 13/100... Step: 840... Loss: 0.267339...
Tuning acc improved(0.828-->0.837). Saving model...
Test acc 0.846
Confusion matrix:
[[19  0]
 [ 6 14]]
Epoch: 18/100... Step: 1210... Loss: 0.324825...
Tuning acc improved(0.837-->0.838). Saving model...
Test acc 0.897
Confusion matrix:
[[19  0]
 [ 4 16]]
Epoch: 24/100... Step: 1630... Loss: 0.291210...
Tuning acc improved(0.838-->0.840). Saving model...
Test acc 0.897
Confusion matrix:
[[19  0]
 [ 4 16]]
Epoch: 37/100... Step: 2520... Loss: 0.414990...
Tuning acc improved(0.840-->0.844). Saving model...
Test acc 0.872
Confusion matrix:
[[19  0]
 [ 5 15]]
Epoch: 40/100... Step: 2730... Loss: 0.296553...
Tuning acc improved(0.844-->0.847). Saving model...
Test acc 0.872
Confusion matrix:
[[19  0]
 [ 5 15]]
Epoch: 50/100... Step: 3440... Loss: 0.327737...
Tuning acc improved(0.847-->0.850).

Epoch: 19/100... Step: 1320... Loss: 0.516300...
Tuning acc improved(0.831-->0.837). Saving model...
Test acc 1.000
Confusion matrix:
[[19  0]
 [ 0 19]]
Epoch: 32/100... Step: 2270... Loss: 0.308954...
Tuning acc improved(0.837-->0.843). Saving model...
Test acc 0.974
Confusion matrix:
[[18  1]
 [ 0 19]]
Epoch: 36/100... Step: 2520... Loss: 0.351307...
Tuning acc improved(0.843-->0.846). Saving model...
Test acc 0.974
Confusion matrix:
[[18  1]
 [ 0 19]]
Epoch: 37/100... Step: 2590... Loss: 0.293274...
Tuning acc improved(0.846-->0.849). Saving model...
Test acc 1.000
Confusion matrix:
[[19  0]
 [ 0 19]]
Epoch: 45/100... Step: 3130... Loss: 0.332970...
Tuning acc improved(0.849-->0.852). Saving model...
Test acc 1.000
Confusion matrix:
[[19  0]
 [ 0 19]]
Epoch: 53/100... Step: 3750... Loss: 0.235411...
Tuning acc improved(0.852-->0.853). Saving model...
Test acc 1.000
Confusion matrix:
[[19  0]
 [ 0 19]]
Epoch: 55/100... Step: 3880... Loss: 0.313624...
Tuning acc improved(0.853-->0.855

Epoch: 1/100... Step: 30... Loss: 0.462209...
Tuning acc improved(0.483-->0.552). Saving model...
Test acc 0.538
Confusion matrix:
[[19  0]
 [18  2]]
Epoch: 1/100... Step: 40... Loss: 0.461991...
Tuning acc improved(0.552-->0.681). Saving model...
Test acc 0.564
Confusion matrix:
[[19  0]
 [17  3]]
Epoch: 1/100... Step: 50... Loss: 0.377268...
Tuning acc improved(0.681-->0.721). Saving model...
Test acc 0.564
Confusion matrix:
[[19  0]
 [17  3]]
Epoch: 2/100... Step: 70... Loss: 0.332736...
Tuning acc improved(0.721-->0.729). Saving model...
Test acc 0.641
Confusion matrix:
[[19  0]
 [14  6]]
Epoch: 2/100... Step: 110... Loss: 0.434285...
Tuning acc improved(0.729-->0.786). Saving model...
Test acc 0.692
Confusion matrix:
[[19  0]
 [12  8]]
Epoch: 4/100... Step: 220... Loss: 0.477527...
Tuning acc improved(0.786-->0.808). Saving model...
Test acc 0.744
Confusion matrix:
[[19  0]
 [10 10]]
Epoch: 9/100... Step: 620... Loss: 0.421207...
Tuning acc improved(0.808-->0.817). Saving model...

Epoch: 5/100... Step: 290... Loss: 0.358071...
Tuning acc improved(0.793-->0.795). Saving model...
Test acc 0.842
Confusion matrix:
[[18  1]
 [ 5 14]]
Epoch: 5/100... Step: 330... Loss: 0.377960...
Tuning acc improved(0.795-->0.801). Saving model...
Test acc 0.868
Confusion matrix:
[[19  0]
 [ 5 14]]
Epoch: 8/100... Step: 520... Loss: 0.269919...
Tuning acc improved(0.801-->0.802). Saving model...
Test acc 0.816
Confusion matrix:
[[15  4]
 [ 3 16]]
Epoch: 8/100... Step: 560... Loss: 0.361797...
Tuning acc improved(0.802-->0.807). Saving model...
Test acc 0.868
Confusion matrix:
[[19  0]
 [ 5 14]]
Epoch: 10/100... Step: 650... Loss: 0.242820...
Tuning acc improved(0.807-->0.822). Saving model...
Test acc 0.816
Confusion matrix:
[[17  2]
 [ 5 14]]
Epoch: 15/100... Step: 1040... Loss: 0.325368...
Tuning acc improved(0.822-->0.823). Saving model...
Test acc 0.895
Confusion matrix:
[[19  0]
 [ 4 15]]
Epoch: 17/100... Step: 1140... Loss: 0.444222...
Tuning acc improved(0.823-->0.838). Saving

Epoch: 12/100... Step: 770... Loss: 0.363544...
Tuning acc improved(0.832-->0.834). Saving model...
Test acc 0.795
Confusion matrix:
[[11  8]
 [ 0 20]]
Epoch: 15/100... Step: 990... Loss: 0.523383...
Tuning acc improved(0.834-->0.847). Saving model...
Test acc 0.769
Confusion matrix:
[[10  9]
 [ 0 20]]
Epoch: 20/100... Step: 1320... Loss: 0.391437...
Tuning acc improved(0.847-->0.858). Saving model...
Test acc 0.821
Confusion matrix:
[[12  7]
 [ 0 20]]
Epoch: 29/100... Step: 1960... Loss: 0.253263...
Tuning acc improved(0.858-->0.859). Saving model...
Test acc 0.795
Confusion matrix:
[[11  8]
 [ 0 20]]
Epoch: 52/100... Step: 3530... Loss: 0.282422...
Tuning acc improved(0.859-->0.861). Saving model...
Test acc 0.744
Confusion matrix:
[[10  9]
 [ 1 19]]
Epoch: 53/100... Step: 3610... Loss: 0.390073...
Tuning acc improved(0.861-->0.862). Saving model...
Test acc 0.744
Confusion matrix:
[[ 9 10]
 [ 0 20]]
Epoch: 56/100... Step: 3800... Loss: 0.204112...
Tuning acc improved(0.862-->0.865).

Epoch: 12/100... Step: 770... Loss: 0.333990...
Tuning acc improved(0.831-->0.834). Saving model...
Test acc 0.897
Confusion matrix:
[[15  4]
 [ 0 20]]
Epoch: 17/100... Step: 1140... Loss: 0.372583...
Tuning acc improved(0.834-->0.835). Saving model...
Test acc 0.872
Confusion matrix:
[[14  5]
 [ 0 20]]
Epoch: 22/100... Step: 1470... Loss: 0.369940...
Tuning acc improved(0.835-->0.837). Saving model...
Test acc 0.923
Confusion matrix:
[[16  3]
 [ 0 20]]
Epoch: 39/100... Step: 2660... Loss: 0.404292...
Tuning acc improved(0.837-->0.840). Saving model...
Test acc 0.872
Confusion matrix:
[[14  5]
 [ 0 20]]
Epoch: 40/100... Step: 2730... Loss: 0.386785...
Tuning acc improved(0.840-->0.841). Saving model...
Test acc 0.872
Confusion matrix:
[[14  5]
 [ 0 20]]
Epoch: 46/100... Step: 3110... Loss: 0.208781...
Tuning acc improved(0.841-->0.843). Saving model...
Test acc 0.872
Confusion matrix:
[[14  5]
 [ 0 20]]
Epoch: 50/100... Step: 3390... Loss: 0.436646...
Tuning acc improved(0.843-->0.849)

Epoch: 39/100... Step: 2690... Loss: 0.420507...
Tuning acc improved(0.843-->0.852). Saving model...
Test acc 0.846
Confusion matrix:
[[15  4]
 [ 2 18]]
Epoch: 46/100... Step: 3170... Loss: 0.388148...
Tuning acc improved(0.852-->0.853). Saving model...
Test acc 0.872
Confusion matrix:
[[16  3]
 [ 2 18]]
cuda:1
87
87
87
test_subject: 41
(2666, 16) (2666,) (667, 16) (667,) (39, 16) (39,)
target train 0/1: 1309/1309
(2666, 7, 16) torch.Size([2666]) (667, 7, 16) torch.Size([667]) (39, 7, 16) torch.Size([39])
<class 'numpy.ndarray'> <class 'torch.Tensor'> <class 'numpy.ndarray'> <class 'torch.Tensor'>
Epoch: 1/100... Step: 10... Loss: 0.617384...
Tuning acc improved(0.000-->0.487). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 1/100... Step: 30... Loss: 0.446258...
Tuning acc improved(0.487-->0.529). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 1/100... Step: 40... Loss: 0.449075...
Tuning acc improved(0.529-->0.654). Saving model.

Epoch: 6/100... Step: 410... Loss: 0.563365...
Tuning acc improved(0.796-->0.804). Saving model...
Test acc 0.538
Confusion matrix:
[[ 1 18]
 [ 0 20]]
Epoch: 7/100... Step: 480... Loss: 0.506483...
Tuning acc improved(0.804-->0.813). Saving model...
Test acc 0.513
Confusion matrix:
[[ 1 18]
 [ 1 19]]
Epoch: 8/100... Step: 550... Loss: 0.360667...
Tuning acc improved(0.813-->0.823). Saving model...
Test acc 0.462
Confusion matrix:
[[ 1 18]
 [ 3 17]]
Epoch: 9/100... Step: 620... Loss: 0.425691...
Tuning acc improved(0.823-->0.831). Saving model...
Test acc 0.487
Confusion matrix:
[[ 1 18]
 [ 2 18]]
Epoch: 17/100... Step: 1170... Loss: 0.493535...
Tuning acc improved(0.831-->0.832). Saving model...
Test acc 0.513
Confusion matrix:
[[ 1 18]
 [ 1 19]]
Epoch: 24/100... Step: 1650... Loss: 0.465421...
Tuning acc improved(0.832-->0.841). Saving model...
Test acc 0.513
Confusion matrix:
[[ 1 18]
 [ 1 19]]
Epoch: 27/100... Step: 1860... Loss: 0.448593...
Tuning acc improved(0.841-->0.849). Savin

Epoch: 8/100... Step: 550... Loss: 0.372992...
Tuning acc improved(0.823-->0.832). Saving model...
Test acc 0.667
Confusion matrix:
[[16  3]
 [10 10]]
Epoch: 17/100... Step: 1170... Loss: 0.466364...
Tuning acc improved(0.832-->0.838). Saving model...
Test acc 0.667
Confusion matrix:
[[16  3]
 [10 10]]
Epoch: 22/100... Step: 1510... Loss: 0.283121...
Tuning acc improved(0.838-->0.843). Saving model...
Test acc 0.667
Confusion matrix:
[[15  4]
 [ 9 11]]
Epoch: 25/100... Step: 1720... Loss: 0.262814...
Tuning acc improved(0.843-->0.844). Saving model...
Test acc 0.667
Confusion matrix:
[[14  5]
 [ 8 12]]
Epoch: 46/100... Step: 3110... Loss: 0.249597...
Tuning acc improved(0.844-->0.849). Saving model...
Test acc 0.692
Confusion matrix:
[[16  3]
 [ 9 11]]
Epoch: 49/100... Step: 3350... Loss: 0.364314...
Tuning acc improved(0.849-->0.855). Saving model...
Test acc 0.692
Confusion matrix:
[[15  4]
 [ 8 12]]
Epoch: 77/100... Step: 5290... Loss: 0.297746...
Tuning acc improved(0.855-->0.856).

cuda:1
87
87
87
test_subject: 48
(2666, 16) (2666,) (667, 16) (667,) (39, 16) (39,)
target train 0/1: 1308/1308
(2666, 7, 16) torch.Size([2666]) (667, 7, 16) torch.Size([667]) (39, 7, 16) torch.Size([39])
<class 'numpy.ndarray'> <class 'torch.Tensor'> <class 'numpy.ndarray'> <class 'torch.Tensor'>
Epoch: 1/100... Step: 10... Loss: 0.645167...
Tuning acc improved(0.000-->0.489). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 1/100... Step: 30... Loss: 0.448562...
Tuning acc improved(0.489-->0.537). Saving model...
Test acc 0.513
Confusion matrix:
[[19  0]
 [19  1]]
Epoch: 1/100... Step: 40... Loss: 0.437448...
Tuning acc improved(0.537-->0.657). Saving model...
Test acc 0.667
Confusion matrix:
[[19  0]
 [13  7]]
Epoch: 1/100... Step: 50... Loss: 0.330151...
Tuning acc improved(0.657-->0.718). Saving model...
Test acc 0.846
Confusion matrix:
[[18  1]
 [ 5 15]]
Epoch: 2/100... Step: 70... Loss: 0.290543...
Tuning acc improved(0.718-->0.760). Saving model...
Tes

Epoch: 2/100... Step: 70... Loss: 0.280716...
Tuning acc improved(0.712-->0.771). Saving model...
Test acc 0.769
Confusion matrix:
[[14  5]
 [ 4 16]]
Epoch: 3/100... Step: 140... Loss: 0.526316...
Tuning acc improved(0.771-->0.784). Saving model...
Test acc 0.513
Confusion matrix:
[[ 0 19]
 [ 0 20]]
Epoch: 4/100... Step: 250... Loss: 0.409041...
Tuning acc improved(0.784-->0.792). Saving model...
Test acc 0.538
Confusion matrix:
[[ 1 18]
 [ 0 20]]
Epoch: 5/100... Step: 290... Loss: 0.535725...
Tuning acc improved(0.792-->0.793). Saving model...
Test acc 0.564
Confusion matrix:
[[ 9 10]
 [ 7 13]]
Epoch: 5/100... Step: 300... Loss: 0.627867...
Tuning acc improved(0.793-->0.801). Saving model...
Test acc 0.462
Confusion matrix:
[[ 5 14]
 [ 7 13]]
Epoch: 5/100... Step: 320... Loss: 0.359508...
Tuning acc improved(0.801-->0.810). Saving model...
Test acc 0.513
Confusion matrix:
[[ 0 19]
 [ 0 20]]
Epoch: 5/100... Step: 340... Loss: 0.370613...
Tuning acc improved(0.810-->0.835). Saving model

Epoch: 36/100... Step: 2420... Loss: 0.341259...
Tuning acc improved(0.849-->0.850). Saving model...
Test acc 0.872
Confusion matrix:
[[14  5]
 [ 0 20]]
Epoch: 37/100... Step: 2520... Loss: 0.318102...
Tuning acc improved(0.850-->0.852). Saving model...
Test acc 0.897
Confusion matrix:
[[15  4]
 [ 0 20]]
Epoch: 52/100... Step: 3560... Loss: 0.357254...
Tuning acc improved(0.852-->0.864). Saving model...
Test acc 0.872
Confusion matrix:
[[14  5]
 [ 0 20]]
Epoch: 61/100... Step: 4170... Loss: 0.256219...
Tuning acc improved(0.864-->0.865). Saving model...
Test acc 0.897
Confusion matrix:
[[15  4]
 [ 0 20]]
Epoch: 72/100... Step: 4910... Loss: 0.284426...
Tuning acc improved(0.865-->0.867). Saving model...
Test acc 0.897
Confusion matrix:
[[15  4]
 [ 0 20]]
Epoch: 88/100... Step: 6030... Loss: 0.247208...
Tuning acc improved(0.867-->0.868). Saving model...
Test acc 0.872
Confusion matrix:
[[14  5]
 [ 0 20]]
Epoch: 96/100... Step: 6580... Loss: 0.462998...
Tuning acc improved(0.868-->0.871

cuda:1
87
87
87
test_subject: 55
(2666, 16) (2666,) (667, 16) (667,) (39, 16) (39,)
target train 0/1: 1308/1308
(2666, 7, 16) torch.Size([2666]) (667, 7, 16) torch.Size([667]) (39, 7, 16) torch.Size([39])
<class 'numpy.ndarray'> <class 'torch.Tensor'> <class 'numpy.ndarray'> <class 'torch.Tensor'>
Epoch: 1/100... Step: 10... Loss: 0.661280...
Tuning acc improved(0.000-->0.489). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 1/100... Step: 30... Loss: 0.445282...
Tuning acc improved(0.489-->0.507). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 1/100... Step: 40... Loss: 0.436474...
Tuning acc improved(0.507-->0.607). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 1/100... Step: 50... Loss: 0.344730...
Tuning acc improved(0.607-->0.670). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 2/100... Step: 70... Loss: 0.316443...
Tuning acc improved(0.670-->0.741). Saving model...
Tes

Epoch: 86/100... Step: 5870... Loss: 0.180600...
Tuning acc improved(0.864-->0.865). Saving model...
Test acc 1.000
Confusion matrix:
[[19  0]
 [ 0 20]]
cuda:1
87
87
87
test_subject: 58
(2667, 16) (2667,) (667, 16) (667,) (38, 16) (38,)
target train 0/1: 1317/1317
(2667, 7, 16) torch.Size([2667]) (667, 7, 16) torch.Size([667]) (38, 7, 16) torch.Size([38])
<class 'numpy.ndarray'> <class 'torch.Tensor'> <class 'numpy.ndarray'> <class 'torch.Tensor'>
Epoch: 1/100... Step: 10... Loss: 0.706577...
Tuning acc improved(0.000-->0.475). Saving model...
Test acc 0.500
Confusion matrix:
[[19  0]
 [19  0]]
Epoch: 1/100... Step: 30... Loss: 0.460558...
Tuning acc improved(0.475-->0.523). Saving model...
Test acc 0.500
Confusion matrix:
[[19  0]
 [19  0]]
Epoch: 1/100... Step: 40... Loss: 0.414183...
Tuning acc improved(0.523-->0.669). Saving model...
Test acc 0.500
Confusion matrix:
[[19  0]
 [19  0]]
Epoch: 1/100... Step: 50... Loss: 0.388651...
Tuning acc improved(0.669-->0.708). Saving model...


Epoch: 4/100... Step: 250... Loss: 0.354011...
Tuning acc improved(0.789-->0.790). Saving model...
Test acc 0.897
Confusion matrix:
[[17  2]
 [ 2 18]]
Epoch: 5/100... Step: 290... Loss: 0.581505...
Tuning acc improved(0.790-->0.799). Saving model...
Test acc 0.923
Confusion matrix:
[[18  1]
 [ 2 18]]
Epoch: 7/100... Step: 420... Loss: 0.516972...
Tuning acc improved(0.799-->0.831). Saving model...
Test acc 0.923
Confusion matrix:
[[18  1]
 [ 2 18]]
Epoch: 9/100... Step: 590... Loss: 0.461014...
Tuning acc improved(0.831-->0.838). Saving model...
Test acc 0.897
Confusion matrix:
[[17  2]
 [ 2 18]]
Epoch: 20/100... Step: 1350... Loss: 0.363560...
Tuning acc improved(0.838-->0.853). Saving model...
Test acc 0.923
Confusion matrix:
[[18  1]
 [ 2 18]]
Epoch: 51/100... Step: 3500... Loss: 0.137137...
Tuning acc improved(0.853-->0.856). Saving model...
Test acc 0.923
Confusion matrix:
[[18  1]
 [ 2 18]]
Epoch: 52/100... Step: 3520... Loss: 0.222334...
Tuning acc improved(0.856-->0.865). Savin

Epoch: 7/100... Step: 420... Loss: 0.541239...
Tuning acc improved(0.825-->0.826). Saving model...
Test acc 0.744
Confusion matrix:
[[13  6]
 [ 4 16]]
Epoch: 8/100... Step: 490... Loss: 0.250494...
Tuning acc improved(0.826-->0.829). Saving model...
Test acc 0.769
Confusion matrix:
[[17  2]
 [ 7 13]]
Epoch: 8/100... Step: 520... Loss: 0.231982...
Tuning acc improved(0.829-->0.840). Saving model...
Test acc 0.795
Confusion matrix:
[[16  3]
 [ 5 15]]
Epoch: 16/100... Step: 1040... Loss: 0.229712...
Tuning acc improved(0.840-->0.867). Saving model...
Test acc 0.821
Confusion matrix:
[[16  3]
 [ 4 16]]
Epoch: 42/100... Step: 2860... Loss: 0.492442...
Tuning acc improved(0.867-->0.874). Saving model...
Test acc 0.769
Confusion matrix:
[[14  5]
 [ 4 16]]
Epoch: 51/100... Step: 3460... Loss: 0.664671...
Tuning acc improved(0.874-->0.877). Saving model...
Test acc 0.769
Confusion matrix:
[[14  5]
 [ 4 16]]
Epoch: 51/100... Step: 3490... Loss: 0.351214...
Tuning acc improved(0.877-->0.879). Sav

Epoch: 1/100... Step: 30... Loss: 0.452142...
Tuning acc improved(0.481-->0.538). Saving model...
Test acc 0.526
Confusion matrix:
[[19  0]
 [18  1]]
Epoch: 1/100... Step: 40... Loss: 0.414720...
Tuning acc improved(0.538-->0.675). Saving model...
Test acc 0.632
Confusion matrix:
[[19  0]
 [14  5]]
Epoch: 1/100... Step: 50... Loss: 0.461783...
Tuning acc improved(0.675-->0.727). Saving model...
Test acc 0.684
Confusion matrix:
[[18  1]
 [11  8]]
Epoch: 2/100... Step: 80... Loss: 0.434006...
Tuning acc improved(0.727-->0.745). Saving model...
Test acc 0.789
Confusion matrix:
[[12  7]
 [ 1 18]]
Epoch: 2/100... Step: 90... Loss: 0.553893...
Tuning acc improved(0.745-->0.762). Saving model...
Test acc 0.763
Confusion matrix:
[[18  1]
 [ 8 11]]
Epoch: 2/100... Step: 120... Loss: 0.309315...
Tuning acc improved(0.762-->0.765). Saving model...
Test acc 0.789
Confusion matrix:
[[18  1]
 [ 7 12]]
Epoch: 3/100... Step: 200... Loss: 0.305583...
Tuning acc improved(0.765-->0.775). Saving model...


Epoch: 1/100... Step: 30... Loss: 0.485856...
Tuning acc improved(0.490-->0.510). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 1/100... Step: 40... Loss: 0.472875...
Tuning acc improved(0.510-->0.636). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 1/100... Step: 50... Loss: 0.312425...
Tuning acc improved(0.636-->0.697). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 2/100... Step: 70... Loss: 0.339422...
Tuning acc improved(0.697-->0.757). Saving model...
Test acc 0.487
Confusion matrix:
[[ 5 14]
 [ 6 14]]
Epoch: 2/100... Step: 120... Loss: 0.497301...
Tuning acc improved(0.757-->0.801). Saving model...
Test acc 0.692
Confusion matrix:
[[12  7]
 [ 5 15]]
Epoch: 5/100... Step: 340... Loss: 0.400519...
Tuning acc improved(0.801-->0.802). Saving model...
Test acc 0.692
Confusion matrix:
[[12  7]
 [ 5 15]]
Epoch: 6/100... Step: 380... Loss: 0.270266...
Tuning acc improved(0.802-->0.808). Saving model...

Epoch: 3/100... Step: 180... Loss: 0.455932...
Tuning acc improved(0.778-->0.798). Saving model...
Test acc 0.744
Confusion matrix:
[[10  9]
 [ 1 19]]
Epoch: 9/100... Step: 560... Loss: 0.574181...
Tuning acc improved(0.798-->0.822). Saving model...
Test acc 0.641
Confusion matrix:
[[ 7 12]
 [ 2 18]]
Epoch: 10/100... Step: 630... Loss: 0.317312...
Tuning acc improved(0.822-->0.835). Saving model...
Test acc 0.667
Confusion matrix:
[[ 8 11]
 [ 2 18]]
Epoch: 11/100... Step: 730... Loss: 0.349032...
Tuning acc improved(0.835-->0.858). Saving model...
Test acc 0.923
Confusion matrix:
[[19  0]
 [ 3 17]]
Epoch: 12/100... Step: 770... Loss: 0.246431...
Tuning acc improved(0.858-->0.870). Saving model...
Test acc 0.872
Confusion matrix:
[[18  1]
 [ 4 16]]
Epoch: 27/100... Step: 1830... Loss: 0.395703...
Tuning acc improved(0.870-->0.873). Saving model...
Test acc 0.897
Confusion matrix:
[[19  0]
 [ 4 16]]
Epoch: 29/100... Step: 1970... Loss: 0.442505...
Tuning acc improved(0.873-->0.874). Savi

Epoch: 2/100... Step: 70... Loss: 0.348571...
Tuning acc improved(0.696-->0.757). Saving model...
Test acc 0.872
Confusion matrix:
[[19  0]
 [ 5 15]]
Epoch: 2/100... Step: 120... Loss: 0.535483...
Tuning acc improved(0.757-->0.763). Saving model...
Test acc 0.744
Confusion matrix:
[[19  0]
 [10 10]]
Epoch: 3/100... Step: 140... Loss: 0.598054...
Tuning acc improved(0.763-->0.769). Saving model...
Test acc 0.872
Confusion matrix:
[[19  0]
 [ 5 15]]
Epoch: 3/100... Step: 160... Loss: 0.443887...
Tuning acc improved(0.769-->0.777). Saving model...
Test acc 0.744
Confusion matrix:
[[19  0]
 [10 10]]
Epoch: 3/100... Step: 200... Loss: 0.420513...
Tuning acc improved(0.777-->0.796). Saving model...
Test acc 0.795
Confusion matrix:
[[17  2]
 [ 6 14]]
Epoch: 7/100... Step: 460... Loss: 0.343351...
Tuning acc improved(0.796-->0.835). Saving model...
Test acc 0.718
Confusion matrix:
[[12  7]
 [ 4 16]]
Epoch: 9/100... Step: 570... Loss: 0.685218...
Tuning acc improved(0.835-->0.838). Saving model

Epoch: 11/100... Step: 730... Loss: 0.338974...
Tuning acc improved(0.843-->0.852). Saving model...
Test acc 0.769
Confusion matrix:
[[13  6]
 [ 3 17]]
Epoch: 17/100... Step: 1110... Loss: 0.344399...
Tuning acc improved(0.852-->0.855). Saving model...
Test acc 0.744
Confusion matrix:
[[16  3]
 [ 7 13]]
Epoch: 17/100... Step: 1130... Loss: 0.458880...
Tuning acc improved(0.855-->0.864). Saving model...
Test acc 0.769
Confusion matrix:
[[16  3]
 [ 6 14]]
Epoch: 18/100... Step: 1200... Loss: 0.315728...
Tuning acc improved(0.864-->0.870). Saving model...
Test acc 0.769
Confusion matrix:
[[16  3]
 [ 6 14]]
Epoch: 19/100... Step: 1270... Loss: 0.261256...
Tuning acc improved(0.870-->0.871). Saving model...
Test acc 0.769
Confusion matrix:
[[15  4]
 [ 5 15]]
Epoch: 20/100... Step: 1330... Loss: 0.284837...
Tuning acc improved(0.871-->0.874). Saving model...
Test acc 0.769
Confusion matrix:
[[16  3]
 [ 6 14]]
Epoch: 55/100... Step: 3750... Loss: 0.497267...
Tuning acc improved(0.874-->0.876)

Epoch: 42/100... Step: 2970... Loss: 0.196263...
Tuning acc improved(0.834-->0.835). Saving model...
Test acc 0.868
Confusion matrix:
[[17  2]
 [ 3 16]]
Epoch: 49/100... Step: 3470... Loss: 0.390562...
Tuning acc improved(0.835-->0.840). Saving model...
Test acc 0.921
Confusion matrix:
[[17  2]
 [ 1 18]]
cuda:1
87
87
87
test_subject: 78
(2666, 16) (2666,) (667, 16) (667,) (39, 16) (39,)
target train 0/1: 1308/1308
(2666, 7, 16) torch.Size([2666]) (667, 7, 16) torch.Size([667]) (39, 7, 16) torch.Size([39])
<class 'numpy.ndarray'> <class 'torch.Tensor'> <class 'numpy.ndarray'> <class 'torch.Tensor'>
Epoch: 1/100... Step: 10... Loss: 0.712535...
Tuning acc improved(0.000-->0.489). Saving model...
Test acc 0.487
Confusion matrix:
[[19  0]
 [20  0]]
Epoch: 1/100... Step: 30... Loss: 0.504118...
Tuning acc improved(0.489-->0.514). Saving model...
Test acc 0.513
Confusion matrix:
[[19  0]
 [19  1]]
Epoch: 1/100... Step: 40... Loss: 0.396940...
Tuning acc improved(0.514-->0.621). Saving model.

cuda:1
87
87
87
test_subject: 80
(2667, 16) (2667,) (667, 16) (667,) (38, 16) (38,)
target train 0/1: 1311/1311
(2667, 7, 16) torch.Size([2667]) (667, 7, 16) torch.Size([667]) (38, 7, 16) torch.Size([38])
<class 'numpy.ndarray'> <class 'torch.Tensor'> <class 'numpy.ndarray'> <class 'torch.Tensor'>
Epoch: 1/100... Step: 10... Loss: 0.804584...
Tuning acc improved(0.000-->0.484). Saving model...
Test acc 0.500
Confusion matrix:
[[19  0]
 [19  0]]
Epoch: 1/100... Step: 20... Loss: 0.526242...
Tuning acc improved(0.484-->0.486). Saving model...
Test acc 0.500
Confusion matrix:
[[19  0]
 [19  0]]
Epoch: 1/100... Step: 30... Loss: 0.438849...
Tuning acc improved(0.486-->0.507). Saving model...
Test acc 0.500
Confusion matrix:
[[19  0]
 [19  0]]
Epoch: 1/100... Step: 40... Loss: 0.379769...
Tuning acc improved(0.507-->0.622). Saving model...
Test acc 0.500
Confusion matrix:
[[19  0]
 [19  0]]
Epoch: 1/100... Step: 50... Loss: 0.527017...
Tuning acc improved(0.622-->0.678). Saving model...
Tes

Epoch: 1/100... Step: 60... Loss: 0.401058...
Tuning acc improved(0.693-->0.697). Saving model...
Test acc 0.526
Confusion matrix:
[[19  0]
 [18  1]]
Epoch: 1/100... Step: 70... Loss: 0.395445...
Tuning acc improved(0.697-->0.706). Saving model...
Test acc 0.526
Confusion matrix:
[[19  0]
 [18  1]]
Epoch: 2/100... Step: 80... Loss: 0.579517...
Tuning acc improved(0.706-->0.763). Saving model...
Test acc 0.579
Confusion matrix:
[[19  0]
 [16  3]]
Epoch: 2/100... Step: 130... Loss: 0.291241...
Tuning acc improved(0.763-->0.772). Saving model...
Test acc 0.816
Confusion matrix:
[[19  0]
 [ 7 12]]
Epoch: 3/100... Step: 180... Loss: 0.278909...
Tuning acc improved(0.772-->0.780). Saving model...
Test acc 0.816
Confusion matrix:
[[19  0]
 [ 7 12]]
Epoch: 4/100... Step: 220... Loss: 0.428571...
Tuning acc improved(0.780-->0.783). Saving model...
Test acc 0.895
Confusion matrix:
[[16  3]
 [ 1 18]]
Epoch: 5/100... Step: 290... Loss: 0.405654...
Tuning acc improved(0.783-->0.787). Saving model..

Epoch: 2/100... Step: 120... Loss: 0.531389...
Tuning acc improved(0.715-->0.798). Saving model...
Test acc 0.923
Confusion matrix:
[[18  1]
 [ 2 18]]
Epoch: 6/100... Step: 350... Loss: 0.294429...
Tuning acc improved(0.798-->0.816). Saving model...
Test acc 0.949
Confusion matrix:
[[19  0]
 [ 2 18]]
Epoch: 9/100... Step: 560... Loss: 0.576849...
Tuning acc improved(0.816-->0.835). Saving model...
Test acc 0.949
Confusion matrix:
[[18  1]
 [ 1 19]]
Epoch: 11/100... Step: 700... Loss: 0.667588...
Tuning acc improved(0.835-->0.837). Saving model...
Test acc 0.949
Confusion matrix:
[[19  0]
 [ 2 18]]
Epoch: 12/100... Step: 770... Loss: 0.345411...
Tuning acc improved(0.837-->0.844). Saving model...
Test acc 0.949
Confusion matrix:
[[19  0]
 [ 2 18]]
Epoch: 29/100... Step: 1940... Loss: 0.574250...
Tuning acc improved(0.844-->0.856). Saving model...
Test acc 0.949
Confusion matrix:
[[18  1]
 [ 1 19]]
Epoch: 30/100... Step: 2010... Loss: 0.338133...
Tuning acc improved(0.856-->0.870). Savin

Epoch: 10/100... Step: 630... Loss: 0.309647...
Tuning acc improved(0.799-->0.819). Saving model...
Test acc 0.744
Confusion matrix:
[[19  0]
 [10 10]]
Epoch: 12/100... Step: 800... Loss: 0.369805...
Tuning acc improved(0.819-->0.835). Saving model...
Test acc 0.846
Confusion matrix:
[[19  0]
 [ 6 14]]
Epoch: 13/100... Step: 870... Loss: 0.378721...
Tuning acc improved(0.835-->0.844). Saving model...
Test acc 0.846
Confusion matrix:
[[19  0]
 [ 6 14]]
Epoch: 16/100... Step: 1040... Loss: 0.268928...
Tuning acc improved(0.844-->0.858). Saving model...
Test acc 0.795
Confusion matrix:
[[18  1]
 [ 7 13]]
Epoch: 17/100... Step: 1110... Loss: 0.286535...
Tuning acc improved(0.858-->0.861). Saving model...
Test acc 0.846
Confusion matrix:
[[19  0]
 [ 6 14]]
Epoch: 28/100... Step: 1920... Loss: 0.236621...
Tuning acc improved(0.861-->0.864). Saving model...
Test acc 0.718
Confusion matrix:
[[17  2]
 [ 9 11]]
Epoch: 33/100... Step: 2240... Loss: 0.371175...
Tuning acc improved(0.864-->0.867). 

In [10]:
print(trained_model_dict['fc1.0.weight'].shape)
print(trained_model_dict['fc1.2.weight'].shape)
print(trained_model_dict['fc1.4.weight'].shape)

torch.Size([32, 15])
torch.Size([16, 32])
torch.Size([6, 16])


In [11]:
print(model.fc1[0].weight.shape)

torch.Size([32, 15])
